services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laraveladmin_app
    #user: www-data
    working_dir: /var/www/html
    volumes:
      - /c/Users/yashvir.pal/Documents/Projects/laraveladmin:/var/www/html:cached
      - laravel_storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache
      #- laravel_build:/var/www/html/public/build

    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=secret

  web:
    image: nginx:alpine
    container_name: laraveladmin_nginx_web
    ports:
      - "8085:80"
    volumes:
      - /c/Users/yashvir.pal/Documents/Projects/laraveladmin:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: laraveladmin_postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: laraveladmin_redis_cache
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: laraveladmin_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: yashvir.pal@kalkine.co.in
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  node:
    image: node:20
    container_name: laraveladmin_node_app
    working_dir: /var/www/html
    volumes:
      - /c/Users/yashvir.pal/Documents/Projects/laraveladmin:/var/www/html
      #- laravel_build:/var/www/html/public/build
    command: sh -c "npm install && npm run dev"
    #command: sh -c "npm install && npm run build"

    depends_on:
      - app    
    ports:
    - "5173:5173"   # Vite default port (optional)  

volumes:
  pgdata:
  pgadmin_data:
  laravel_storage:  # <--- define here
  laravel_cache:    # <--- define here
  #laravel_build:
